version: "3.8"

services:
  pdf-service:
    image: ${REGISTRY:-localhost}/pdf-service:${TAG:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 2G
      restart_policy:
        condition: on-failure
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
    environment:
      - WORKERS=1
      - TESSERACT_NUM_THREADS=2
      - MAX_WORKERS=2
      - PYTHONUNBUFFERED=1
      - MALLOC_ARENA_MAX=2
      - PYTHONMALLOC=malloc
      - REDIS_URL=redis://redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - pdf-network

  redis:
    image: redis:alpine
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    networks:
      - pdf-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      replicas: 1
    depends_on:
      - pdf-service
    networks:
      - pdf-network

networks:
  pdf-network:
    driver: overlay
